name: Veracode SAST - Pipeline Scan

on:
    push:
        branches:
        - '*'

jobs:

    Build:
        runs-on: ubuntu-latest
        steps:

          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - name: Checking Out Code Repo
            uses: actions/checkout@v2

          - name: Installing Pre-Reqs
            run: |
              echo "Installing pre-reqs..."
              sudo apt-get update && sudo apt-get install -y curl unzip grep

          - name: Downloading Veracode CLI
            run: |
              echo '[INFO] --- Downloading Veracode CLI (Latest Version)...'
              curl -fsS -O https://tools.veracode.com/veracode-cli/install
              chmod +x ./install
              ./install
              if [ -f "./veracode" ]; then
                chmod +x veracode
                ./veracode version
              else
                echo "[ERROR] Veracode CLI was not successfully installed!"
                exit 1
              fi

          - name: Packaging Artifacts
            run: |
              echo "[INFO] --- Packaging artifacts to be scanned"
              export VERACODE_API_KEY_ID=$VID
              export VERACODE_API_KEY_SECRET=$VKEY
              ./veracode package --source . --output ./verascan/ --trust
            env:
              VID: ${{ SECRETS.VID }}
              VKEY: ${{ SECRETS.VKEY }}

          - name: Running Veracode SAST - Pipeline Scan
            run: |
              echo "[INFO] --- Running Veracode SAST - Pipeline Scan"
              export VERACODE_API_KEY_ID=$VID
              export VERACODE_API_KEY_SECRET=$VKEY
              ./veracode static scan ./verascan/veracode-auto-pack-*-js.zip --results-file results.json --summary-output summary_results.txt --fail-on-severity "Very High, High"
            env:
              VID: ${{ SECRETS.VID }}
              VKEY: ${{ SECRETS.VKEY }}

          - name: Results Validation
            if: always()
            run: |
              cat summary_results.txt

              if [ ! -f "summary_results.txt" ]; then
                echo "[INFO] --- There are no flaws in the artifact!!" > payload.json
              else
                # Use summary_results.txt to prepare the payload.json file
                echo "{\n" > payload.json
                while IFS= read -r myLine; do
                  echo "\t\"text\": \"$myLine"\" > payload.json
                done < summary_results.txt
                echo "\n}" > payload.json
              fi
              cat payload.json
              curl -X POST -H 'Content-type: application/json' --data '{"text":"Testing this process!"}' $SLACK_WEBHOOK_URL
            env:
              SLACK_WEBHOOK_URL: ${{ SECRETS.SLACK_WEBHOOK_URL }}

          # Publishing artifacts - Payload file
          - name: Publishing Payload File
            if: success()
            uses: actions/upload-artifact@v4
            with: 
              name: mySlackPayloadArtifact
              path: ./payload.json
